import { Router } from "express";
import userRoutes from "./user.routes";
import imageRoutes from "./image.routes";
import likeRoutes from "./like.routes";
import listBadWordsRoutes from "./listBadWords.routes";
import listGoodWordsRoutes from "./listGoodWords.routes";
import postRoutes from "./post.routes";
import replyRoutes from "./reply.routes";
import reportRoutes from "./report.routes";
import roleRoutes from "./role.routes";
import tagRoutes from "./tag.routes";
import authRoutes from "./auth.routes";
import dashboardDataRoutes from "./dashboardData.routes";
import commonWordRoutes from "./commonWords.queries";
const router = Router();
router.use("/user", userRoutes);
router.use("/posts", postRoutes);
router.use("/replies", replyRoutes);
router.use("/images", imageRoutes);
router.use("/likes", likeRoutes);
router.use("/badwords", listBadWordsRoutes);
router.use("/goodwords", listGoodWordsRoutes);
router.use("/reports", reportRoutes);
router.use("/roles", roleRoutes);
router.use("/tags", tagRoutes);
router.use("/auth", authRoutes);
router.use("/dashboard", dashboardDataRoutes);
router.use("/commonwords", commonWordRoutes);
export default router;